### ISSUE TITLE
Cannot log in until i logged into Web Yahoo Messenger

### ISSUE THREAD

**Issue by gradinaruvasile** [EionRobb/funyahoo-plusplus#10]
Hi,
In the description you stated that if you cannot log in, "try logging into yahoo mail in a browser".
It seems that logging into webmail is not enough (still prompted me after that to log into my account), i had to to log in/launch the Web Yahoo Messenger also to let me log in from Pidgin.

**Comment by noob2020** [comment]
me too

**Comment by EionRobb** [comment]
That should have said "logged into messenger.yahoo.com once"

I've updated the plugin with the new error message, but haven't updated the readme just yet

**Comment by dequis** [comment]
Done that readme change in ee886aca0690a24401e037851c28a6e042b072e2
