### ISSUE TITLE
KDialog closed unexpectedly

### ISSUE THREAD

**Issue by AdmFubar** [EionRobb/funyahoo-plusplus#15]
This happened durring the make install., using kde 5.5.5, qt 5.5.1 kernel 4.1.27-27 opensuse leap

Application: KDialog (kdialog), signal: Aborted
Using host libthread_db library "/lib64/libthread_db.so.1".
[KCrash Handler]
#6  0x00007f2bcb5680c7 in raise () at /lib64/libc.so.6
#7  0x00007f2bcb569478 in abort () at /lib64/libc.so.6
#8  0x00007f2bccbb36d4 in qt_message_output(QtMsgType, char const*) () at /usr/lib64/libQtCore.so.4
#9  0x00007f2bcd64a089 in  () at /usr/lib64/libkdeui.so.5
#10 0x00007f2bcd721f68 in  () at /usr/lib64/libkdeui.so.5
#11 0x00007f2bcd72293b in KApplication::KApplication(bool) () at /usr/lib64/libkdeui.so.5
#12 0x000000000040b171 in  ()
#13 0x00007f2bcb554b25 in __libc_start_main () at /lib64/libc.so.6
#14 0x000000000040e721 in _start ()

i think i need to add this 

make install
mkdir -p `pkg-config --variable=plugindir purple`
install -p libyahoo-plusplus.so `pkg-config --variable=plugindir purple`

PARAMETERS:

system folder for script /usr/local/bin/
local folder for script /root/bin
prefix: /usr
local prefix: /root/.kde4/

menu entry 

the KDialog error happens right before the  menu entry line. that only shows up after a ^c.

**Comment by EionRobb** [comment]
No idea why there's any KDE stuff in there at all, the plugin doesn't use it, Pidgin doesn't use it and the make script certainly doesn't either

**Comment by AdmFubar** [comment]
I submitted a bug report with KDE. I'll hopefully will hear something from  
them.

**Comment by AdmFubar** [comment]
ok problem was it didnt get copied correctly, I manually copied it and it  
works

**Comment by dequis** [comment]
This makes no sense to me. Either way, closing, it wasn't an issue with this plugin anyway.
