### ISSUE TITLE
re: Plugin and legacy Pidgin version

### ISSUE THREAD

**Issue by denovoid** [EionRobb/funyahoo-plusplus#20]
Thank you for this plugin -- I have the plugin apparently working on Pidgin v 2.10.11 on an XP machine and have sent a message to a buddy, but have not yet had the opportunity to test if it has been received or whether I am able to obtain replies yet.

MAIN QUESTION -- I also use Pidgin v 2.6.6 on an old Win98 machine where the old Yahoo was working fine, along with AIM --  but this 2016 plugin does not show up on the dropdown list of available account types there with the dll in place. Is this something that might be fixable at some point?

**Comment by EionRobb** [comment]
I was initially going to say "I don't think Pidgin 2.6.6 has the functions we use in the plugin to be able to make this work" but just for fun I tried compiling against that version of Pidgin and it didn't complain about any missing functions.  It might be more to do with the version of libjson-glib-1.0.dll and the glib/gtk that ships with that really really (really) out of date version of Pidgin

Just out of curiosity, can you try open the debug log (Help->Debug Window) then leave that open and open the plugins list (Tools->Plugins) then close the plugins list, and attach the output of the debug window to this issue?

**Comment by denovoid** [comment]
[PIDGIN - GITHUB.txt](https://github.com/EionRobb/funyahoo-plusplus/files/452349/PIDGIN.-.GITHUB.txt)
I think the last 2 lines tell the story - alas it's not too specific.

**Comment by dequis** [comment]
Unless eion wants to keep digging here, I'm closing this. Not much that can be done - json-glib has a relatively high glib requirement and it's possible that your version of pidgin ships an old glib, or that newer glib versions dropped support for win 9x.
