### ISSUE TITLE
Old messages with links appear at every login

### ISSUE THREAD

**Issue by Shdwdrgn** [EionRobb/funyahoo-plusplus#22]
Pulled Yahoo(2016) from github at 8:30MDT on Sept 2.
Every time time I sign in to the new yahoo, I get a window that pops up with 'missed' messages, however what it is showing me are messages that I have in fact seen.  Messages from one person were actually seen under the new Yahoo web chat interface, and messages from another person were from last May.

The one detail about these errant messages is that they are all URL links.  I don't get notified of any comments that are just plan text.

Let me know if you need any details from the debug log, but this issue should be easy to reproduce... Have someone send you a URL, then close and restart pidgin.

**Comment by dequis** [comment]
Fixed with 44df619ed477b803fda54cc74bdcad6a76b3ecc0, thanks!

**Comment by Shdwdrgn** [comment]
Confirmed fixed, thanks!
