### ISSUE TITLE
Can not send or recieve Message using LinuxMint

### ISSUE THREAD

**Issue by geniuswithaces** [EionRobb/funyahoo-plusplus#23]
After removing the version in the repository (was older version) i downloaded the Current version, installed the dependencies required and Old yahoo worked (before it was pulled), Gmail Works, Face-book Works as well as AOL.

I Installed the new Yahoo(2016) it showed in the drop down list,  But i can not Send or Receive  any Yahoo Messages.

Using the Web-mail app in Linux I can send and receive, Using the New Yahoo app i can send receive in Windows and OSX

**Comment by dequis** [comment]
Buddy list -> help menu -> debug window. After opening it, send a message, and copy/paste what the debug window shows after you sent that message.

**Comment by geniuswithaces** [comment]
I attached it for you...

its called purple-debug.log

**Comment by dequis** [comment]
Uh, github dropped the attachment, i think. Attach it frm the website (using the thing that says "Attach files by dragging & dropping or selecting them" below the comment form)

**Comment by geniuswithaces** [comment]
[purple-debug.log.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/453152/purple-debug.log.tar.gz)

**Comment by EionRobb** [comment]
```
yahoo: got frame data: {"msg":"ChannelProtocolError","reason":"Client ack 173 exceeds server seq 2"}
```
Is the important bit from the log. And it'll be stuck in a loop too.

**Comment by EionRobb** [comment]
Unfortunately the debug log misses the part when you tried to send the message so we can't see the exact cause of you getting stuck in the loop. I imagine its the groupId:null issue that we're seeing elsewhere

**Comment by geniuswithaces** [comment]
if you need for me to run the debug again, or some other diagnostics i will. just let me know what you need.  if you need hardware info i can run the commands in a terminal window and save in a text file, i believe there is also a way to list all of the packages on my system as well via synaptic as well.

**Comment by EionRobb** [comment]
Was the buddy you were trying to send a message to a buddy that you haven't messaged with the new plugin before?

**Comment by geniuswithaces** [comment]
it was a buddy, that i have messaged in the past with old protocol on pidgin.  I also was able to send that buddy a im via webmail on linuxmint as well as the new yahoo messenger in both OSX and in Windows10.

**Comment by EionRobb** [comment]
And that's why I specifically asked whether it was someone you had messaged with the new plugin on pidgin. :) 

Is that a "yes, I haven't messaged them from pidgin with the new plugin".?

**Comment by geniuswithaces** [comment]
new yahoo(2016) plugin has not functioned properly yet on linuxmint or on my windows 10 boxes.

**Comment by cambies** [comment]
Hi, i have the same problem.  Can't send or receive messages to any contacts after using this plugin on Linux Mint 18. Buddy list is showing duplicates that i can't delete either.  Log attached of opening msg window then sending a message.  appears to send ok, but doesn't.

cheers
[purple-debug.log.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/453217/purple-debug.log.tar.gz)

**Comment by siffegh** [comment]
Same problem, Win7  Pro SP1.  Had to interrupt the log.
[pidgin.pdf](https://github.com/EionRobb/funyahoo-plusplus/files/453793/pidgin.pdf)

tx,

Ed

**Comment by geniuswithaces** [comment]
here is a debug when i tried to use the windows version via wine on the same box..... 
[ViaWIne.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/454396/ViaWIne.tar.gz)

**Comment by siffegh** [comment]
Hi, is there any hope of getting this working?

**Comment by geniuswithaces** [comment]
what additional information is needed to help troubleshooting... perhaps  a list of installed apps and a hardware used?   
[packages-installed.list.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/465040/packages-installed.list.tar.gz)
[sysinfo3 (noserials).txt.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/465041/sysinfo3.noserials.txt.tar.gz)

**Comment by dequis** [comment]
Please try again with the latest revision, it may fix a relevant issue.

For windows users, I made this build http://dequis.org/libyahoo-plusplus.dll, should show up with version string `0.9.2016.09.10.git.r56.e9aff87` in the plugin information window. Eion will probably update the more-official url later.

**Comment by geniuswithaces** [comment]
no difference in windows box or on linux under wine.

**Comment by dequis** [comment]
Well, first, I trying under wine is pointless. Just build the linux binary with the instructions in the README.

Second, reviewing old attachments of this thread:

1. @geniuswithaces's [first log][a1] from [this comment][c1] is precisely the issue that i fixed in b7477bdd72564bc06bcf91026c87f6c308ab32c5 - and if this issue or an equivalent one was still present, you'd get more visible errors that disconnect the whole account
2. @cambies's [log][a2] from [this comment][c2] has no errors at all. The message is sent, the server acks the message.
3. @siffegh's [log][a3] from [this comment][c3], same thing as the previous one, no errors, message acked by the server.
4. @geniuswithaces's [log via wine][a4] from [this comment][c4] is a wine crash at exit, with no actual pidgin debug log.
5. The other two attachments from [this comment][c5] are not relevant.

So, as far as I can see, there's no issue anymore.

Please check in the web client to see if the sent message is visible in the conversation corresponding to this contact.

[a1]: https://github.com/EionRobb/funyahoo-plusplus/files/453152/purple-debug.log.tar.gz
[c1]: https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-244522812
[a2]: https://github.com/EionRobb/funyahoo-plusplus/files/453217/purple-debug.log.tar.gz
[c2]: https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-244529382
[a3]: https://github.com/EionRobb/funyahoo-plusplus/files/453793/pidgin.pdf
[c3]: https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-244584489
[a4]: https://github.com/EionRobb/funyahoo-plusplus/files/454396/ViaWIne.tar.gz
[c4]: https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-244657484
[c5]: https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-246072113

**Comment by siffegh** [comment]
Thanks, it is working for me now with the new dll - but only after disabling the Off-The-Record Messaging plugin.

**Comment by geniuswithaces** [comment]
i tried with the DLL on a windows box as well as my linuxbox running wine with pidgin,  perhaps with the updated source i can recompile for my linuxbox.  if you need for me to run something and send you the output i will, just let me have the procedure that you need for me to use.  Perhaps i need some additional dependancy from a repository.  The version of Pidgin that i am using on the linuxmint box was downloaded from pidgin,im and i followed the instructions to compile and install it (since the latest version available from the repo was 2.10 not 2.11)

**Comment by geniuswithaces** [comment]
the error i see in the debug windows i...  nss: partial certificate chain
[linuxdebug.log.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/465755/linuxdebug.log.tar.gz)

**Comment by dequis** [comment]
@geniuswithaces can you confirm the version string shown by "Yahoo (2016)" in Help -> Plugin information?

**Comment by geniuswithaces** [comment]
here are the linxmint screenshopts.... 
![about pidgin linux](https://cloud.githubusercontent.com/assets/21956994/18415300/69d0597e-77bb-11e6-8680-b33d864e7719.png)
![linux accts](https://cloud.githubusercontent.com/assets/21956994/18415301/6b65c760-77bb-11e6-9ab1-f881242c2724.png)
![pidgin-linux-info](https://cloud.githubusercontent.com/assets/21956994/18415302/6da8f556-77bb-11e6-8a52-6936083fb1dd.png)

**Comment by dequis** [comment]
It says "0.9". That is still the old version.

**Comment by geniuswithaces** [comment]
now from wine......
![acctswine](https://cloud.githubusercontent.com/assets/21956994/18415331/0d044772-77bc-11e6-9cda-db672259e8bc.png)
![wine-about](https://cloud.githubusercontent.com/assets/21956994/18415332/0e5c3738-77bc-11e6-8147-aed53c6d841f.png)
![wine-plugin](https://cloud.githubusercontent.com/assets/21956994/18415333/0fa6a57e-77bc-11e6-88c0-cd525603c371.png)

**Comment by geniuswithaces** [comment]
yes i dont have the new source for the .so to compile the new version for linux...  but is does not work in either version.

**Comment by dequis** [comment]
You might want to read https://github.com/EionRobb/funyahoo-plusplus#how-to-compile-for-linux - the second command is a way to get the source.

Can I have a debug log from an installation that is not the old version?

**Comment by geniuswithaces** [comment]
i ran the commands...  and the compile finished and i put it into the proper directory.  are you asking for the purple-debug log from linux?  using pidgin 2.11 with yahoo(2016) ?  it already uploaded.  do you need for me to run something again?

**Comment by dequis** [comment]
The last debug log had "linuxdebug.log.tar.gz" as the filename. Your linux mint screenshots showed that you had version 0.9. If you still haven't figured out how to upgrade the version, don't use the linux mint one.

The wine stuff shows the correct version. Debug logs from that version are acceptable.

**Comment by geniuswithaces** [comment]
sigh....   i am using linuxmint 18 sarah...  the version of pidgin is 2.11 ( which i downloaded from pidgin.im) compiled and installed.  I then used the command on the libyahoo-plusplus and that is version the older version.  has the files that get cloned been updated?   i can recompile when the new code is there.   i put the information here so you can see that niether worked (linux does not use the dll, it needs a .so file instead)
Neither the Windows or Linux version are working for me.

**Comment by geniuswithaces** [comment]
[purple-debug-new.log.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/466194/purple-debug-new.log.tar.gz)

**Comment by dequis** [comment]
There are no errors in that log. The server acknowledges the message.

Is the message visible in https://messenger.yahoo.com/group/GIOFI6ZYBFDDZKRU5WPQ6UJYLM ?

If so, is that URL accessible from the main contact list?

**Comment by geniuswithaces** [comment]
I can see it when i paste the URL into a browser
i cant send any messages using Yahoo2016 either from Linuxmint Native, or when using Wine (Windows Emulator) Windows Version.  If you think the newer version may fix it it linux, please update the conntents of the git Clone package.

**Comment by dequis** [comment]
If you click the information icon on the top-right corner of the web messenger, does the sidebar that appears look roughly like this?

![](http://dump.dequis.org/Q_azh.png)

**Comment by geniuswithaces** [comment]
yes, i see that when using web messenger. i clear the old conversations all the time.

**Comment by dequis** [comment]
I mean, does it look like that in [the URL I linked][1]? Or does it look different?

[1]: https://messenger.yahoo.com/group/GIOFI6ZYBFDDZKRU5WPQ6UJYLM

**Comment by geniuswithaces** [comment]
i just sent a message from webversion to pidg
![screenshot from 2016-09-11 18-19-26](https://cloud.githubusercontent.com/assets/21956994/18420945/54597b3e-784c-11e6-850b-03ecb3f4213d.png)
in_test

**Comment by dequis** [comment]
Oh, maybe i should have mentioned, that's not my account and i'm not really sure who owns it, I just throw garbage at it sometimes.

So I've been testing this "clear conversation" thing and it seems this issue affects the official client too.

Say Alice and Bob are having a conversation with the web client

* Alice does "clear conversation", which wipes the server side logs and the conversation is hidden from the UI.
* Bob doesn't get notified of this.
* When Bob tries to talk to that conversation, Alice doesn't see those messages.
* If Alice accesses the /group/ URL directly, she can see those messages.
* If Alice tries to start a new conversation by searching for Bob and sending a message, she gets that /group/ URL again with the messages that were sent by Bob.
* Even after doing this, Bob never appears again in the recent conversations list of Alice.
* When Alice doesn't have that conversation open, the messages from Bob are practically lost.

So, don't use the "clear conversation" feature, it's buggy and will break things.

If the other person used this and the messages aren't getting through, the only thing I can suggest is to start a named groupchat with only one member.

**Comment by dequis** [comment]
b026686f82b376188157000d0b5a1a96cca8ba8f might help with the case of conversations that have only one member, which is similar but not quite the same thing I mentioned in my previous comment. But like that one, it sounds a lot like the sort of thing that is yahoo's fault, so not holding my breath here. 

Either way please try the latest revision of http://dequis.org/libyahoo-plusplus.dll and report results.

**Comment by geniuswithaces** [comment]
-the reason why i delete the old messages is so they dont reload each time.  it avoids the beeps and loads faster, perhaps that is why there are duplicate ids in the list of names.  
- I seem to be getting some messages using the Windows Emulator (WINE) with the Windows version of pidgin.   It is super slow and the messages dont always arrive (i have connected to other boxes remotely(teamviewer) and watch the response time).  
-The Update did not hit the GitClone yet,  i am awaiting the source to update then recompile the .so on the linux side.

**Comment by dequis** [comment]
>The Update did not hit the GitClone yet, i am awaiting the source to update then recompile the .so on the linux side.

Are you trying to do anything for it to update, or just waiting? Cloning doesn't configure automagic synchronzation for you. It just downloads a repository once.

The normal way to update a git repository is `git pull`

But even without knowing this, it's not too crazy to try re-running the commands you know, and if you see `fatal: destination path '...' already exists and is not an empty directory.`, maybe consider deleting the directory and starting from scratch?

**Comment by geniuswithaces** [comment]
this is what i used....  
sudo apt-get install libpurple-dev libjson-glib-dev libglib2.0-dev git make;
git clone https://github.com/EionRobb/funyahoo-plusplus.git && cd funyahoo-plusplus;
make && sudo make install
 and yes i create new directory for the clone each time...  last i checked its still 0.9

**Comment by dequis** [comment]
Post the output of the `make && sudo make install` line.

Also run `which pidgin` and post the output of that too.

**Comment by geniuswithaces** [comment]
[funyahoo-plusplus.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/468596/funyahoo-plusplus.tar.gz)

**Comment by dequis** [comment]
Sorry, by "output" I meant what those commands show in the terminal after running them.

**Comment by geniuswithaces** [comment]
harvey-HP-Pavilion-dv7-Notebook-PC yahoo-pidgin091216 # sudo apt-get install libpurple-dev libjson-glib-dev libglib2.0-dev git make;
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1).
libjson-glib-dev is already the newest version (1.1.2-0ubuntu1).
make is already the newest version (4.1-6).
libglib2.0-dev is already the newest version (2.48.1-1~ubuntu16.04.1).
libpurple-dev is already the newest version (1:2.10.12-0ubuntu5.1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
harvey-HP-Pavilion-dv7-Notebook-PC yahoo-pidgin091216 # git clone https://github.com/EionRobb/funyahoo-plusplus.git && cd funyahoo-plusplus;
Cloning into 'funyahoo-plusplus'...
remote: Counting objects: 177, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 177 (delta 11), reused 0 (delta 0), pack-reused 155
Receiving objects: 100% (177/177), 80.87 KiB | 0 bytes/s, done.
Resolving deltas: 100% (104/104), done.
Checking connectivity... done.
harvey-HP-Pavilion-dv7-Notebook-PC funyahoo-plusplus # make && sudo make installcc -fPIC -O2 -g -pipe -Wall -DYAHOO_PLUGIN_VERSION='"0.9.2016.09.12.git.r60.701a697"' -shared -o libyahoo-plusplus.so libyahoo-plusplus.c -Wl,-z,relro `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
mkdir -p `pkg-config --variable=plugindir purple`
install -p libyahoo-plusplus.so `pkg-config --variable=plugindir purple`
harvey-HP-Pavilion-dv7-Notebook-PC funyahoo-plusplus #

**Comment by geniuswithaces** [comment]
still shows...   0.9
as the version in about plugins

**Comment by dequis** [comment]
Please run 

    which pidgin

And also

    pkg-config --variable=plugindir purple

And post the output of both commands.

**Comment by EionRobb** [comment]
and double-check that there's not an old version of the plugin in the `pkg-config --variable=plugindir purple` directory, nor the ~/.purple/plugins dir

**Comment by geniuswithaces** [comment]
LinuxMint18 Sarah 
harvey@harvey-HP-Pavilion-dv7-Notebook-PC ~ $ pkg-config --variable=plugindir purple
/usr/local/lib/purple-2
harvey@harvey-HP-Pavilion-dv7-Notebook-PC ~ $ 

![search](https://cloud.githubusercontent.com/assets/21956994/18460569/a6a4845c-7940-11e6-88ec-518726c3720a.png)
![plugininfo](https://cloud.githubusercontent.com/assets/21956994/18460576/ad5b12f2-7940-11e6-9583-0625b7b475a3.png)
![pidgin-version](https://cloud.githubusercontent.com/assets/21956994/18460579/b0a764ba-7940-11e6-9d57-9f8b50bc4fb1.png)

**Comment by dequis** [comment]
Please run 

    which pidgin

That's a command. You write that in a terminal.

**Comment by EionRobb** [comment]
I'm still suspect of the 'Yahoo (2016)' being right at the top of the list there, that it's being loaded from ~/.purple/plugins

**Comment by geniuswithaces** [comment]
Pidgin 2.11.0 For Linux.. i downloaded and compiled it. it works with AOL. Facebook, Google... But NOT the New Yahoo.

Why do you think being at the top of the list matters?

**Comment by geniuswithaces** [comment]
I just checked what you were saying about the order.....   found a older version located  in /home/harvey/.purple/plugins  i deleted it and the new File says its loaded...  **Great catch.**

obviously it looks to load from /home/harvey/.purple/plugins (home folder first)

harvey@harvey-HP-Pavilion-dv7-Notebook-PC ~ $ pkg-config --variable=plugindir purple
/usr/local/lib/purple-2
harvey@harvey-HP-Pavilion-dv7-Notebook-PC ~ $ which pidgin
/usr/local/bin/pidgin
harvey@harvey-HP-Pavilion-dv7-Notebook-PC ~ $ 

Hopefully that was the issue.... I will test and see what happens.

**Comment by dequis** [comment]
Neat. @EionRobb wins this round.

**Comment by geniuswithaces** [comment]
lol..  it wasnt a fight.    but here is a explanation why it did not show up when i searched for it..   http://unix.stackexchange.com/questions/21778/whats-so-special-about-directories-whose-names-begin-with-a-dot   I will be testing to see if i can see why some things dont  get to its destination. perhaps its from the removal of past conversation as was mentioned earlier.. if that is the case, is there a way to clear them without causing other issues?

**Comment by geniuswithaces** [comment]
fyi.. i do get this....  Server error: "Client skipped ahead (frame.seq=2, numResent=-1, numAcked=1, clientSeq=1)". If this keeps happening, report a bug. Try to include the debug window messages before the error happens.

i also get.... Upstream unavailable

I think its from timing out

Should i Close this and open a Different Ticket? 

[purple-debug.log.tar.gz](https://github.com/EionRobb/funyahoo-plusplus/files/470472/purple-debug.log.tar.gz)
 

Perhaps some kind of Keep alive is needed or some way to handle when computer goes into Power Saving / Energy Conservations Mode ?

**Comment by dequis** [comment]
>Server error: "Client skipped ahead (frame.seq=2, numResent=-1, numAcked=1, clientSeq=1)".

Fixed in b1440a0610cabe9271ebc9f9649d3af534443e5d

>Upstream unavailable

That's server downtime.

**Comment by geniuswithaces** [comment]
Great Job Guys  !!!  I have been using it and only have occasional glitches witch i think are from the yahoo server side.  I do have one other question..... I know that Pidgin and Adium are "related"  because they both use lib-purple. I believe Adium uses Cocoa,  would you happen to have a script i can use to compile it to use in Adium on OSX?

**Comment by dequis** [comment]
Adium uses libpurple in a weird way that requires plugins to have some sort of wrapper that someone has to write. I don't really understand it and don't have a mac to help with that, so all we can do is wait for someone to contribute that wrapper.

Also, glad to hear things are better now! Closing this as fixed then.
