### ISSUE TITLE
Constantly writing to disk

### ISSUE THREAD

**Issue by alexolog** [EionRobb/funyahoo-plusplus#25]
... which makes the system significantly less responsive.

Please see http://pastebin.com/9t7ijKrK for a 1-second activity log.

**Comment by dequis** [comment]
This is fixed by fe2a944f50ddf6b88618439d8b62d7c3b60669f2, please ensure you're using the latest revision

@EionRobb built the latest dll already?

**Comment by alexolog** [comment]
I am running under Windows and don't have the setup to build from source.
Eion's DLLs do not include version information and there is not indication when they were built and from which commit.

**Comment by dequis** [comment]
Looks like it got another build a couple of days ago. Try again.

Also, are you serious when you say that writing 50 kilobytes every few seconds makes your system less responsive? That makes no sense to me.

**Comment by alexolog** [comment]
It's not 50kb every few seconds, it's opening files 100 times per second.  The disk is constantly seeking and it is noticeable on my old and underpowered computer..
The DLL that I downloaded fixed it.
Specifying the date when the DLL was built is a good thing.

**Comment by dequis** [comment]
What tool did you use to generate that log?

**Comment by alexolog** [comment]
https://technet.microsoft.com/en-ca/sysinternals/processmonitor

**Comment by dequis** [comment]
The rest of this issue should be handled by e9aff878889c70841d6a30bfa89e1c29afac15c4.
