### ISSUE TITLE
After some minutes, messages are not sent or received and debug window shows infinite messages

### ISSUE THREAD

**Issue by hotice** [EionRobb/funyahoo-plusplus#28]
Using the latest funyahoo-plusplus from Git in Ubuntu 16.04, with Pidgin 2.10.12, after a few minutes, messages are no longer sent or received, and the debug window shows pretty much the same stuff over and over again indefinitely and it scrolls like crazy.  This is what's displayed in the debug window:
```
(14:17:21) nss: partial certificate chain
(14:17:21) certificate/x509/tls_cached: Starting verify for prod.iris.yahoo.com
(14:17:21) certificate/x509/tls_cached: Checking for cached cert...
(14:17:21) certificate/x509/tls_cached: ...Found cached cert
(14:17:21) nss/x509: Loading certificate from /home/andrei/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(14:17:21) certificate/x509/tls_cached: Peer cert matched cached
(14:17:21) nss/x509: Exporting certificate to /home/andrei/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(14:17:21) util: Writing file /home/andrei/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(14:17:21) nss: Trusting CN=*.iris.yahoo.com,OU=Information Technology,O=Yahoo Inc.,L=Sunnyvale,ST=California,C=US
(14:17:21) certificate: Successfully verified certificate for prod.iris.yahoo.com
(14:17:22) yahoo: frame_len: 77
(14:17:22) yahoo: got frame data: {"msg":"ChannelProtocolError","reason":"Client ack 488 exceeds server seq 5"}
(14:17:22) dnsquery: Performing DNS lookup for prod.iris.yahoo.com
(14:17:22) dns: Successfully sent DNS request to child 18146
(14:17:22) dns: Got response for 'prod.iris.yahoo.com'
(14:17:22) dnsquery: IP resolved for prod.iris.yahoo.com
(14:17:22) proxy: Attempting connection to 63.250.200.45
(14:17:22) proxy: Connecting to prod.iris.yahoo.com:443 with no proxy
(14:17:22) proxy: Connection in progress
(14:17:22) proxy: Connecting to prod.iris.yahoo.com:443.
(14:17:22) proxy: Connected to prod.iris.yahoo.com:443.
(14:17:22) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(14:17:22) nss: subject=CN=*.iris.yahoo.com,OU=Information Technology,O=Yahoo Inc.,L=Sunnyvale,ST=California,C=US issuer=CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US
```
To see it start, all I have to do is open the debug window and wait, after some time it always starts to scroll like crazy and that's when messages are no longer sent/received. The time for this to start happening varies. The last time it happened after about 5 minutes, but before that it occurred after about half an hour of opening Pidgin (with Yahoo 2016 as the only account enabled).

**Comment by hotice** [comment]
The bug didn't occur for the past ~2 hours, so I guess it's related to Yahoo's servers. But if that's the case, it seems the server just drops the connection and then it works again, but Pidgin never reconnects. That's because every time this happened (4-5 times in about 1,5 hours), restarting Pidgin or disabling and re-enabling the Yahoo account got it to work immediately. So if it's possible, maybe you can implement a way to reconnect automatically (obviously, only if this affects more people)?

**Comment by sammyjava** [comment]
Reproduced here, on Ubuntu 16. Person on other end gets a disconnect message from Yahoo, but I see nothing. (I'm not running in debug mode.)

**Comment by dequis** [comment]
This is handled by e9aff878889c70841d6a30bfa89e1c29afac15c4. Please open new tickets if you're getting new errors from that.
