### ISSUE TITLE
Yahoo (2016) Protocol Missing

### ISSUE THREAD

**Issue by SarcasticWit** [EionRobb/funyahoo-plusplus#29]
First, thank you for this plug-in...

Now if I can get it to work...

I have downloaded the 2 dll files and unpacked the zip file and placed all in the plugins directory, however, I am not getting the option to select Yahoo (2016)...

Am I missing something?

Thanks again...

**Comment by dequis** [comment]
From the readme:

>download libjson-glib-1.0.dll and place that into Program Files\Pidgin - not the plugins folder.)

Not the plugins folder.

**Comment by MariusStuparu** [comment]
Still does not appear. I have placed the `libjson-glib-1.0.dll` in `C:\Program Files (x86)\Pidgin` and the `libyahoo-plusplus.dll` in `C:\Program Files (x86)\Pidgin\plugins`, but the new protocol still does not appear. I have version 2.11.0 installed.

**Comment by dequis** [comment]
Even after restarting pidgin?

If it still doesn't work, can you open the debug log (Help->Debug Window) then leave that open and open the plugins list (Tools->Plugins) then close the plugins list, and attach the output of the debug window to this issue?

**Comment by MariusStuparu** [comment]
I restarted Pidgin several times. Here's the debug output.

[Pastebin](http://pastebin.com/F1iJRpKc)

The "missing" `perl.dll` is actually present in the filesystem.

**Comment by dequis** [comment]
Can you put that `C:\Program Files (x86)\Pidgin\plugins\libyahoo-plusplus.dll` in a .zip file, and attach it here? With the thing below the github comment form.

**Comment by MariusStuparu** [comment]
Yep, here it is: [libyahoo-plusplus.dll.zip](https://dl.dropboxusercontent.com/u/629003/libyahoo-plusplus.dll.zip)

**Comment by dequis** [comment]
Stupid proxies.

That dll actually contains an html file with this text:

```
   Internet Access WARNING - Acceptable Use Compliance

   Access to this site is not be permitted by the [2]Oracle Acceptable Use
   Policy.

          This website has a Security Reputation Rating of High Risk.
      It is a known site for malicious software distribution and malicious
                                    intent.

   Malware, or malicious software, is software designed to infect your
   computer for the purpose of secretly gathering information and/or to gain
   access to your computer to conduct illegal activities.

   Phishing emails, such as Shipment Deliveries or Faxes are another source
   of infections and malicious URLs that may coax you into accessing this
   site.

   For more information on malware and website reputation, see the [3]Warning
   Banner FAQ, located on the GIT Risk Management site.

   This warning is to help prevent your computer from becoming infected with
   malware.

   [4][ Click here if you have read and understood the policy and wish to
   access this site. ]

   If you believe the Reputation is incorrect, please email sites@mcafee.com
   and request to have the URL reviewed.

   Alert: This website has a Security Reputation Rating of High Risk
   URL: http://eion.robbmob.com/libyahoo-plusplus.dll
   Category:
   Site Reputation: High Risk
   Code: Reputation Coaching
```

Bunch of scary text, but it's a false positive. I don't know about mcafee in particular but that website got into the blacklists of some antiviruses because of this portion of html in the main page:

```

<h2 style="clear:left">Legacy Skype API Plugin</h2>
<script>
document.write('<p><a href="#legacy" onclick="document.getElementById(\'legacy\').style.display=\'block\';">Click here<'+'/a> to view information about the old, legacy skype plugin<'+'/p>');
</script>
```

If you know some basic html you can tell how dumb this whole situation is. I guess someone at an antivirus company really doesn't like document.write(). We've already reported a few false positives, I didn't know mcafee did this too.

Anyway the link to the latest build is now http://dequis.org/libyahoo-plusplus.dll (i also updated the readme) so maybe that helps. Once the whole thing is stable we'll release it on github.

**Comment by MariusStuparu** [comment]
Hah, dind't check the actual contents. It works now, thanks. Shame I don't have the groups anymore, but at least I have time to migrate anyone.

**Comment by dequis** [comment]
Yay!
