### ISSUE TITLE
Add versioned release, please

### ISSUE THREAD

**Issue by msdobrescu** [EionRobb/funyahoo-plusplus#31]
As it is not clear when a new binary is released, please add some information related to the version, on the page, please.

**Comment by EionRobb** [comment]
Not quite stable enough for a version release yet. Too many "cannot send/receive messages" bugs to sort out before that. Once the main ones are fixed I'll make sure we do a proper release 

For now the dll is updated almost in-step with commits. Checking the file modified/created time is probably the best way to tell for now.

**Comment by msdobrescu** [comment]
Regardless the stability, it is useful to know a build number at least, to know it is or not updated, or a date when the dll was built last time...

**Comment by dequis** [comment]
I usually check the Last-Modified date of the file with `curl -I` but no idea how a windows user would do this.

```
$ curl -I http://eion.robbmob.com/libyahoo-plusplus.dll
HTTP/1.1 200 OK
Date: Wed, 07 Sep 2016 13:48:09 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Tue, 06 Sep 2016 06:28:26 GMT
Accept-Ranges: bytes
Content-Length: 306460
Content-Type: application/x-msdos-program
```

I dunno, maybe https://www.hurl.it/?method=HEAD&url=http://eion.robbmob.com/libyahoo-plusplus.dll ? Feels like there should be a better way.

**Comment by dequis** [comment]
The next build will have a version string like `0.9.2016.09.10.git.r54.1521167` visible from help -> plugin information
