### ISSUE TITLE
Add instructions to build for Windows

### ISSUE THREAD

**Issue by Bearded-Blunder** [EionRobb/funyahoo-plusplus#33]
Easy for Linux users to keep current with developments given the posted instructions on how to compile, but Windows is my main platform. Building *under* Linux (in a VM) is no issue.. but how? .dll file linked lags way behind commits.

**Comment by dequis** [comment]
The build environment setup instructions are in https://developer.pidgin.im/wiki/BuildingWinPidgin

Once you do that, adjust paths in the first four or five lines of the makefile (ignore pidgin3 stuff) to match your setup and 'make'.

FWIW I uploaded my build here http://dequis.org/libyahoo-plusplus.dll
