### ISSUE TITLE
protocol tx&rx'ing a few kilobytes/second most of the time.

### ISSUE THREAD

**Issue by AdmFubar** [EionRobb/funyahoo-plusplus#35]
I've not clocked it to see exactly when it starts, but after some time there is constant stream of traffic with this protocol. Is this normal for the new protocal? 12+KB/s is a lot of traffic over time, as I leave my system running all the time.

**Comment by dequis** [comment]
Smells like d3244eb5215ffa8bd775dcdd164edd386c0a5dcc

**Comment by Bearded-Blunder** [comment]
I get this too after a while, the debug log goes crazy:
[Debug log.txt](https://github.com/EionRobb/funyahoo-plusplus/files/518643/Debug.log.txt)
This may be the start of one of the runaways:
[Debug 2.txt](https://github.com/EionRobb/funyahoo-plusplus/files/518646/Debug.2.txt)
The value of X in "Client ack 15 exceeds server seq X" is sometimes different, I've seen both 2 or 4, once it starts it just keeps on endlessly till I restart Pidgin.

**Comment by dequis** [comment]
@Bearded-Blunder Please open a new ticket, that is not the same issue. Also ensure you're using the latest revision.
