### ISSUE TITLE
Retrieve Yahoo username instead of raw ID or alias

### ISSUE THREAD

**Issue by rensdewolf** [EionRobb/funyahoo-plusplus#37]
Would it be possible to retrieve the username of a buddy? At the moment all you see is the friendly alias or the 26 character raw ID. Or is it not possible with this 'new' protocol?

**Comment by dequis** [comment]
Yeah, not possible as far as i know. @EionRobb what do you think?

**Comment by EionRobb** [comment]
Only thing I can think of is including the email/yid/phone in the buddy tooltip if the info is provided to us

**Comment by dequis** [comment]
>if the info is provided to us

Yeah, that "if" is the problem. I don't think i've seen it.

**Comment by EionRobb** [comment]
It shows up if that's the method you've added someone, in order to link between email/yid/phone and their guid

**Comment by rensdewolf** [comment]
My question was about someone else sending you a message. Now all you see is his/her name, initials and guid. I have looked at the websocket (push) messages and did not find anything else in there, so I guess this issue can be closed.
(It seems Yahoo makes it easy to impersonate someone as you can easily set your name to anything and it's unlikely people will know or ask for the guid or yahoo id to verify who their talking to. Oh well...)
