### ISSUE TITLE
Offline buddies showing online

### ISSUE THREAD

**Issue by cericson46** [EionRobb/funyahoo-plusplus#40]
Running Pidgin 2.10.12. I build the plugin for the new Yahoo protocol. It seems to be working fine but have not had a lot of activity as yet. However, the buddy list is showing a whole list of buddies supposedly online and ready. By chatting with them via other means I have confirmed that most of them are not online. The names are consistently the same over several days and logins. Is this an issue at Yahoo IM or with the new plugin? What other info can I provide? My XMPP plugin is working as before.

**Comment by EionRobb** [comment]
Unfortunately that's a new "feature" of Yahoo.  from [their faq](https://web.archive.org/web/20160730080614/https://help.yahoo.com/kb/yahoo-messenger-for-web/SLN26860.html):
"How can I tell if someone is online or not?
Right now, there's no presence indicator that shows when your contacts are online. However, you can now message anyone, even if they're offline. They'll receive a mobile notification with your message. Think of it like text messaging!"

**Comment by cericson46** [comment]
Another one of those adorable "features". Thanks for the quick response. Keep up the good work.
