### ISSUE TITLE
yahoo 2016 not showing in dropdown using Ubuntu 16.10 with Pidgin 2.12.0

### ISSUE THREAD

**Issue by geniuswithaces** [EionRobb/funyahoo-plusplus#45]
It worked in Yaketty using Pidgin 2.10...  Facebook stopped working so i overwrote 2.10 with 2.12 and got Facebook to work, however Yahoo2016 does not show in dropdown. i used the script from your webpage. if you need for me to do screen captures let me know i will do the screen captures and post them... thanks.

**Comment by geniuswithaces** [comment]
the problem was that i did not uninstall first. after i did a make uninstall etc... i moved the extracted tar.gz files.  and did a sudo apt-get remove pidgin..  rebooted and eventually got it to work.   I did notice when i ran your script, it put the number 3 in the .so , after seeing that is when i decided to try to uninstall the the files.  perhaps a warning  or a greater emphasis in the install instructions about the need to uninstall first?

**Comment by dequis** [comment]
Glad you figured it out
