### ISSUE TITLE
Couldn't get login cookies

### ISSUE THREAD

**Issue by Squire136** [EionRobb/funyahoo-plusplus#47]
(20:06:46) account: Connecting to account user@example.com.
(20:06:46) connection: Connecting. gc = 05F4FEA0
(20:06:46) util: requesting to fetch a URL
(20:06:46) dnsquery: Performing DNS lookup for login.yahoo.com
(20:06:46) dnsquery: IP resolved for login.yahoo.com
(20:06:46) proxy: Attempting connection to 98.136.189.41
(20:06:46) proxy: Connecting to login.yahoo.com:443 with no proxy
(20:06:46) proxy: Connection in progress
(20:06:46) proxy: Connecting to login.yahoo.com:443.
(20:06:46) proxy: Connected to login.yahoo.com:443.
(20:06:46) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(20:06:46) nss: subject=CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(20:06:46) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(20:06:46) nss: subject=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(20:06:46) certificate/x509/tls_cached: Starting verify for login.yahoo.com
(20:06:46) certificate/x509/tls_cached: Checking for cached cert...
(20:06:46) certificate/x509/tls_cached: ...Found cached cert
(20:06:46) nss/x509: Loading certificate from C:\Users\USER\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(20:06:46) certificate/x509/tls_cached: Peer cert matched cached
(20:06:46) nss/x509: Exporting certificate to C:\Users\USER\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(20:06:46) util: Writing file C:\Users\USER\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(20:06:46) nss: Trusting CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(20:06:46) certificate: Successfully verified certificate for login.yahoo.com
(20:06:46) g_log: yahoo_string_get_chunk: assertion `chunk_start' failed
(20:06:46) connection: Connection error on 05F4FEA0 (reason: 0 description: Couldn't get login cookies)
(20:06:46) account: Disconnecting account user@example.com (02705288)
(20:06:46) connection: Disconnecting connection 05F4FEA0
(20:06:46) jabber: jabber_actions: have pep: NO
(20:06:46) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\yahoo.png: Failed to open file 'C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\yahoo.png': No such file or directory
(20:06:46) connection: Destroying connection 05F4FEA0

**Comment by dequis** [comment]
Tried logging in through the website?

**Comment by Shdwdrgn** [comment]
I've been getting the same thing all day from both computers (Couldn't get login cookies).  Their web chat works fine though.

**Comment by alexolog** [comment]
Same problem here.

Logging to messenger.yahoo.com works, but Pidgin fails with "Couldn't get login cookies"

Log: https://pastebin.com/TJJvLxqy

**Comment by alexolog** [comment]
And as quickly as it came, it's gone again.
Works normally for me today.

**Comment by Shdwdrgn** [comment]
Mine auto-reconnected again sometime overnight.  I wonder if any changes were made to their servers?

**Comment by dequis** [comment]
Interesting. They rolled back the changes they made yesterday.

**Comment by Squire136** [comment]
This plugin is now working for me as well. I am closing this issue and will re-open or create a new one if it happens again.

**Comment by EionRobb** [comment]
Easiest bugfix evarrrrr 👍

**Comment by Shdwdrgn** [comment]
You had to say that, didn't you?  The bug appears to be back again, yahoo disconnected within the last few hours with "Couldn't get login cookies" and I cannot seem to reconnect.

**Comment by cgomez1** [comment]
I have the same error from some hours ago.

10:50:43) g_log: yahoo_string_get_chunk: assertion 'chunk_start' failed
(10:50:43) connection: Connection error on 0x55c8093f3ea0 (reason: 0 description: Couldn't get login cookies)
(10:50:43) account: Disconnecting account xxxxx (0x55c806c7df50)

**Comment by dequis** [comment]
Fix 3c7adf6dc3675553942417f715c9b55bc714a25a

Version string 0.9.2017.06.24.git.r70.3c7adf6

DLL in the usual location http://dequis.org/libyahoo-plusplus.dll

Yahoo sucks

**Comment by Shdwdrgn** [comment]
(Notes comment on latest commit) You work on it because we all have that ONE friend who can't be convinced how badly Yahoo chat sucks now?  Well I certainly appreciate the work you do, so thank you.

Latest version installed, connected without any problems.

**Comment by cgomez1** [comment]
Thank you! After install the latest version, this plugin is now working for me.

**Comment by tiggerfan** [comment]
yahoo/verizon broke it again :(
