### ISSUE TITLE
Unknown error -- invalid crumb

### ISSUE THREAD

**Issue by alexolog** [EionRobb/funyahoo-plusplus#48]
Using the latest DLL.
Link to log: https://pastebin.com/r1SymZxL

Apparently uses the wrong crumb.

**Comment by Squire136** [comment]
Same issue here. Also signed in through a browser and confirmed that was working for the same account.

**Comment by macexpertsusa** [comment]
same issue - latest DLL also

**Comment by dequis** [comment]
Fix a9524315465f85c9524f1bbd41d2c0f55d5e7530

Version string 0.9.2017.07.06.git.r73.a952431

DLL in the usual location http://dequis.org/libyahoo-plusplus.dll

Yahoo sucks
