### ISSUE TITLE
Session Expired Error

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/funyahoo-plusplus#51]
I am now getting a "Session Expired" Error on Yahoo PlusPlus.

**Comment by ljakab** [comment]
Same here, I've been getting that error for a few weeks now.

**Comment by Zombie-Ryushu** [comment]
Got it again. Can't make it go away this time.

**Comment by Squire136** [comment]
I am having the same problem. Here is the Debug Window output set to Level: ALL:

(18:17:47) account: Connecting to account USER@yahoo.com.
(18:17:47) connection: Connecting. gc = 06354A28
(18:17:47) yahoo: Fetching url https://login.yahoo.com/?done.=https%3A%2F%2Fmessenger.yahoo.com%2F
(18:17:47) dnsquery: Performing DNS lookup for login.yahoo.com
(18:17:47) dnsquery: IP resolved for login.yahoo.com
(18:17:47) proxy: Attempting connection to 98.136.189.41
(18:17:47) proxy: Connecting to login.yahoo.com:443 with no proxy
(18:17:47) proxy: Connection in progress
(18:17:47) proxy: Connecting to login.yahoo.com:443.
(18:17:47) proxy: Connected to login.yahoo.com:443.
(18:17:47) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(18:17:47) nss: subject=CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:47) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:47) nss: subject=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:47) certificate/x509/tls_cached: Starting verify for login.yahoo.com
(18:17:47) certificate/x509/tls_cached: Checking for cached cert...
(18:17:47) certificate/x509/tls_cached: ...Found cached cert
(18:17:47) nss/x509: Loading certificate from C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:47) certificate/x509/tls_cached: Peer cert matched cached
(18:17:47) nss/x509: Exporting certificate to C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:47) util: Writing file C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:47) nss: Trusting CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(18:17:47) certificate: Successfully verified certificate for login.yahoo.com
(18:17:47) g_log: purple_url_encode: assertion `str != NULL' failed
(18:17:47) yahoo: Fetching url https://login.yahoo.com/?.done=https%3A%2F%2Fmessenger.yahoo.com%2F
(18:17:47) yahoo: With postdata username=USER%40yahoo.com&acrumb=R8urMS8h&config=zrADBBT.2Ypk6j5dS2qxIUgSq0_b2UygcVlPdTO8ssUbzASH7p7qEHoaoPeSFm6q7c9KiLhWaAX.8DFp8If6QEU1VJrquAQ3351XK8mmWOgppiFLqGIBuQr1ibE_6g_pLel0W2keVnQh2Hz0HJBDylTq3gBQThpuzoIsX9EYbPj7TlhupHZEpryYVpJYAFdsb1vQUGeMlsgH2PQiLHNHpxHF_Edp~A&session=(null)&
(18:17:47) dnsquery: Performing DNS lookup for login.yahoo.com
(18:17:47) dnsquery: IP resolved for login.yahoo.com
(18:17:47) proxy: Attempting connection to 98.136.189.41
(18:17:47) proxy: Connecting to login.yahoo.com:443 with no proxy
(18:17:47) proxy: Connection in progress
(18:17:47) proxy: Connecting to login.yahoo.com:443.
(18:17:47) proxy: Connected to login.yahoo.com:443.
(18:17:48) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(18:17:48) nss: subject=CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) certificate/x509/tls_cached: Starting verify for login.yahoo.com
(18:17:48) certificate/x509/tls_cached: Checking for cached cert...
(18:17:48) certificate/x509/tls_cached: ...Found cached cert
(18:17:48) nss/x509: Loading certificate from C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) certificate/x509/tls_cached: Peer cert matched cached
(18:17:48) nss/x509: Exporting certificate to C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) util: Writing file C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) nss: Trusting CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(18:17:48) certificate: Successfully verified certificate for login.yahoo.com
(18:17:48) g_log: purple_url_encode: assertion `str != NULL' failed
(18:17:48) g_log: purple_url_encode: assertion `str != NULL' failed
(18:17:48) yahoo: Fetching url https://login.yahoo.com/account/challenge/fail?authMechanism=primary&display=login&yid=&done=https%3A%2F%2Fmessenger.yahoo.com%2F&eid=100&acrumb=R8urMS8h
(18:17:48) yahoo: With postdata username=USER%40yahoo.com&password=yahooSecuritySucks12&acrumb=R8urMS8h&config=(null)&s=(null)&verifyPassword=Sign%C2%A0in
(18:17:48) dnsquery: Performing DNS lookup for login.yahoo.com
(18:17:48) dnsquery: IP resolved for login.yahoo.com
(18:17:48) proxy: Attempting connection to 98.136.189.41
(18:17:48) proxy: Connecting to login.yahoo.com:443 with no proxy
(18:17:48) proxy: Connection in progress
(18:17:48) proxy: Connecting to login.yahoo.com:443.
(18:17:48) proxy: Connected to login.yahoo.com:443.
(18:17:48) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(18:17:48) nss: subject=CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) certificate/x509/tls_cached: Starting verify for login.yahoo.com
(18:17:48) certificate/x509/tls_cached: Checking for cached cert...
(18:17:48) certificate/x509/tls_cached: ...Found cached cert
(18:17:48) nss/x509: Loading certificate from C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) certificate/x509/tls_cached: Peer cert matched cached
(18:17:48) nss/x509: Exporting certificate to C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) util: Writing file C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\login.yahoo.com
(18:17:48) nss: Trusting CN=login.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(18:17:48) certificate: Successfully verified certificate for login.yahoo.com
(18:17:48) GLib: g_str_has_prefix: assertion `str != NULL' failed
(18:17:48) yahoo: Fetching url https://prod.iris.yahoo.com/prod/rpc?wait=1&v=1&crumb=
(18:17:48) yahoo: With postdata {"msg":"OpenSession","device":{"kind":"mobile"},"auth":{"provider":"signin"},"version":{"platform":"web","app":"iris/dogfood","appVersion":929},"batch":[]}
(18:17:48) dnsquery: Performing DNS lookup for prod.iris.yahoo.com
(18:17:48) dnsquery: IP resolved for prod.iris.yahoo.com
(18:17:48) proxy: Attempting connection to 63.250.200.45
(18:17:48) proxy: Connecting to prod.iris.yahoo.com:443 with no proxy
(18:17:48) proxy: Connection in progress
(18:17:48) proxy: Connecting to prod.iris.yahoo.com:443.
(18:17:48) proxy: Connected to prod.iris.yahoo.com:443.
(18:17:48) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(18:17:48) nss: subject=CN=*.iris.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) nss: subject=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(18:17:48) certificate/x509/tls_cached: Starting verify for prod.iris.yahoo.com
(18:17:48) certificate/x509/tls_cached: Checking for cached cert...
(18:17:48) certificate/x509/tls_cached: ...Found cached cert
(18:17:48) nss/x509: Loading certificate from C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\prod.iris.yahoo.com
(18:17:48) certificate/x509/tls_cached: Peer cert matched cached
(18:17:48) nss/x509: Exporting certificate to C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\prod.iris.yahoo.com
(18:17:48) util: Writing file C:\Users\ME\AppData\Roaming\.purple\certificates\x509\tls_peers\prod.iris.yahoo.com
(18:17:48) nss: Trusting CN=*.iris.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
**(18:17:48) certificate: Successfully verified certificate for prod.iris.yahoo.com
(18:17:49) connection: Connection error on 06354A28 (reason: 0 description: Session expired)
(18:17:49) account: Disconnecting account USER@yahoo.com (027096E8)**
(18:17:49) connection: Disconnecting connection 06354A28
(18:17:49) jabber: jabber_actions: have pep: NO
(18:17:49) connection: Destroying connection 06354A28

**Comment by dequis** [comment]
Uh. Someone else fix it. Thanks.

**Comment by cgomez1** [comment]
I've been getting that error for a few days now..

Here is the Debug Window output (summary)

(10:22:40) certificate/x509/tls_cached: Starting verify for prod.iris.yahoo.com
(10:22:40) certificate/x509/tls_cached: Checking for cached cert...
(10:22:40) certificate/x509/tls_cached: ...Found cached cert
(10:22:40) nss/x509: Loading certificate from /home/username/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(10:22:40) certificate/x509/tls_cached: Peer cert matched cached
(10:22:40) nss/x509: Exporting certificate to /home/username/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(10:22:40) util: Writing file /home/username/.purple/certificates/x509/tls_peers/prod.iris.yahoo.com
(10:22:40) nss: Trusting CN=*.iris.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(10:22:40) certificate: Successfully verified certificate for prod.iris.yahoo.com
(10:22:41) http: Request 0xa689de78a0 performed without success.
(10:22:41) yahoo: Got response: {"msg":"InvalidCredentials"}
(10:22:41) connection: Connection error on 0xa68a779560 (reason: 0 description: Session expired)
(10:22:41) account: Disconnecting account usernamecu (0xa68a67efc0)
(10:22:41) connection: Disconnecting connection 0xa68a779560
(10:22:41) connection: Destroying connection 0xa68a779560
(10:22:41) util: Writing file accounts.xml to directory /home/username/.purple
(10:22:41) util: Writing file /home/username/.purple/accounts.xml
(10:22:41) util: Writing file blist.xml to directory /home/username/.purple
(10:22:41) util: Writing file /home/username/.purple/blist.xml

**Comment by tiggerfan** [comment]
the plugin has stopped working for me about a week now.  I've tried redownload  and recompile and no luck.

**Comment by EionRobb** [comment]
f95917580f3876a586bc184921e07a31e3f76c6a 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10223160-299905203_11-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by tiggerfan** [comment]
thanks that got it.

**Comment by dequis** [comment]
Uploaded new dll, version string `0.9.2017.09.08.git.r74.f959175`

**Comment by Zombie-Ryushu** [comment]
Got another session expired error just today.

**Comment by RodMyers** [comment]
same as Zombie-Ryushu

**Comment by cgomez1** [comment]
same as Zombie-Ryushu too

**Comment by Zombie-Ryushu** [comment]
Has this changed for anyone?

**Comment by dequis** [comment]
It ain't gonna fix itself

**Comment by tiggerfan** [comment]
its back.....

**Comment by cgomez1** [comment]
Hi guys, 
any update on this issue?  I've tried re-download and recompile and no luck. I got the same error.

Thank you!

**Comment by EionRobb** [comment]
Unfortunately in the spare hour I had to look into this, I wasn't able to work out what changes are needed to make the authentication work

**Comment by NoOneGitHub** [comment]
Is this plugin dead? . I hate Yahoo, but it's a necessary evil.
I've been having this issue for a few weeks now.

**Comment by Zombie-Ryushu** [comment]
The plugin is not dead. EionRobb would fix it if he knew what the issue was. There have been several attempts, they have all failed. A wall has been hit, and additional people need to analyze the protocol from the Apps to find out what the problem is. This is basically cat and mouse.

**Comment by NoOneGitHub** [comment]
I'd offer help, but that's not my skillset. I would assume most of the issues originate with all of the certificate changes Yahoo and the new owner have been implementing to get from under the compromised access. They have had a number of short duration certificates and even the current one has a December 2017 expiry.

**Comment by isgbuddy** [comment]
I still get 

(13:31:51) util: Writing file D:\App\PidginPortable\Data\settings\.purple\certificates\x509\tls_peers\prod.iris.yahoo.com
(13:31:52) nss: Trusting CN=*.iris.yahoo.com,O=Yahoo! Inc.,L=Sunnyvale,ST=CA,C=US
(13:31:52) certificate: Successfully verified certificate for prod.iris.yahoo.com
(13:31:52) http: Request 04B6DF70 performed without success.
(13:31:52) yahoo: Got response: {"msg":"InvalidCredentials"}

**Comment by DeepMac** [comment]
Same issue here, have never been able to get in. Can login to messenger.yahoo.com directly.

I expect this is Yahoo! making changes on the back-end.

**Comment by macexpertsusa** [comment]
any chance someone can figure this out - still inoperative Nov 21  - thanks in advance

**Comment by Zombie-Ryushu** [comment]
I know. We need more people looking into this. Because the Module at this point, crashes Pidgin. As long as it just EionRobb, it won't get done because EionRobb has is hands full with other things.

**Comment by macexpertsusa** [comment]
hi Zombie - anyone else have the skillset and time  to look into this - I used to code but its been a while, would take a long time to get into the details with any hope of deciphering what's going on - been almost another month so I was just checking in again to see if there were any updates...would love to see this going again - all the best

**Comment by Zombie-Ryushu** [comment]
To the best of my knowledge, nobody has worked on this. Furthermore, I have not recieved a single E-mail from a YIM User who now Uses Yahoo Messenger. If there are "survivors" on Yahoo Messanger, I would be very suprised. I'd like to see this plugin completed because:

1. I would like to be able to say we have it, even though again, its pointless because I think when YIM went offline, I think everyone jumped ship, there may be holdouts.
2. There may still be survivors. I lost alot of good people on YIM. Unlike with AIM, where I had time to go gather up all the hold-outs, with YIM, everything happened much too fast for me to get alternative contact info for everyone.
3. YM is focused on Android and iOS, not any desktop platforms. The software is effectively location and datamining Malware, as opposed to YIM which was more Adware. We should do this to try and let Yahoo know we won't take this laying down.

**Comment by macexpertsusa** [comment]
All very good points, thanks for reply

YM is still working inside the webpage for yahoo mail so there is a chance that those who are still using yahoo mail will jump back into using YM again I would think - at least a chance I hope.

AIM shutdown was really unnecessary IMHO

Did you see what they did with their AOL Desktop?  

I was not getting persistent crashes using the last plugin compile but I did get a few - usually it just wouldn't connect

Hope someone can find the time and the will to get it working again

**Comment by Zombie-Ryushu** [comment]
No, I was never a Windows user and I never actually used AIM or YIM's actual Windows applications when they were current. I always just used Pidgin (Gaim) for pretty much everything. Except IRC which I used HexChat/XChat.

**Comment by dequis** [comment]
I think this was fixed by #62
