### ISSUE TITLE
YIM Buddies appear as a persistently online when they are not. 

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/funyahoo-plusplus#56]
YIM Buddies appear as a persistently online when they are not. in some instances, it can appear that all of a given YIM User's buddies are online at once. In addition, sometimes old fragments of conversations can be replayed or multiple empty chat windows to old YIM Buddies can be open upon successful Authentication.

**Comment by dequis** [comment]
> Thus there are [several features that the new protocol doesn't have](https://web.archive.org/web/20160730080614/https://help.yahoo.com/kb/yahoo-messenger-for-web/SLN26860.html):
> 
>   *  Typing notifications
>   *  Away/Idle statuses
>   *  Your old buddy list
>   *  Bold/italic/underline formatting

The link:

> How can I tell if someone is online or not?
> 
> Right now, there's no presence indicator that shows when your contacts are online. However, you can now message anyone, even if they're offline. They'll receive a mobile notification with your message. Think of it like text messaging!
