### ISSUE TITLE
Crashes after adding account

### ISSUE THREAD

**Issue by RevStrangeHope** [EionRobb/funyahoo-plusplus#61]
Pidgin Fully crashes after adding account unsure what is causing this. hope this information proves useful.

```
System Info
OS: Ubuntu 16.04.3 LTS x86_64
Kernel: 4.4.0-112-generic
DE: Xfce
WM: Xfwm4
```

**Comment by dequis** [comment]
Duplicate of #61

**Comment by RevStrangeHope** [comment]
what are you on about? this isn't a Duplicate

**Comment by dequis** [comment]
Oh sorry I wrote the wrong ticket number. #57
