### ISSUE TITLE
Where are the offline buddies?

### ISSUE THREAD

**Issue by dbeusee** [EionRobb/funyahoo-plusplus#7]
Thanks much for the plugin!  I can only see online buddies with this plugin.  I need all buddies in the buddy list.  I got the dll from issue #1.

-Don

**Comment by dequis** [comment]
It's a limitation of the new protocol. From [this link from the README][1]:

>How can I tell if someone is online or not?
>
>Right now, there's no presence indicator that shows when your contacts are online. However, you can now message anyone, even if they're offline. They'll receive a mobile notification with your message. Think of it like text messaging!

[1]: https://web.archive.org/web/20160730080614/https://help.yahoo.com/kb/yahoo-messenger-for-web/SLN26860.html

**Comment by dbeusee** [comment]
Well, if that's true, I don't understand why I don't see all the contacts then.  With that weakness, I'd expect to see all contacts and none of them would show as online.  But instead I see only the online contacts.  How is it limiting to the online contacts if there's no presence indicator?

**Comment by EionRobb** [comment]
That will also be the only buddies on your buddy list that are in the new messenger system (see point 3 on the " several features that the new protocol doesn't have" list)

You can add the other buddies using the Buddies->Add Buddy menu option from the buddy list

**Comment by dbeusee** [comment]
I tried to add the other buddies, but when I restarted pidgin, they were gone.
